name = "glitterapp"
main = "./functions/api/generate.js"
compatibility_date = "2024-03-31"
workers_dev = true

[site]
bucket = "."

[build]
command = ""

[build.upload]
format = "modules"
main = "./functions/api/generate.js"

[env.production]
name = "glitterapp-prod" 