name = "glittertxt"
main = "dist/_worker.js"
compatibility_date = "2024-03-31"

[site]
bucket = "./dist"

[build]
command = "./build.sh"
watch_dir = "dist"

[[env.production.services]]
name = "FLASK_APP"
service = "glittertxt"
environment = "production" 